export default [
  { displayName: '序号', name: 'serialNumber', width: 100 },
  { displayName: '合同编号', name: 'contractNumber', width: 100 },
  { displayName: '项目编号', name: 'projectNumber', width: 100 },
  { displayName: '项目名称', name: 'projectName', width: 100 },
  { displayName: '合同名称', name: 'contractName', width: 100 },
  { displayName: '合同甲方', name: 'contractPartyA', width: 100 },
  { displayName: '合同乙方', name: 'contractPartyB', width: 100 },
  { displayName: '所在地', name: 'location', width: 100 },
  { displayName: '行业', name: 'industry', width: 100 },
  { displayName: '签订日', name: 'signingDate', width: 100 },
  { displayName: '生效日', name: 'effectiveDate', width: 100 },
  { displayName: '结束日', name: 'endDate', width: 100 },
  { displayName: '有效期\n(年)', name: 'validityPeriodInYears', width: 100 },
  { displayName: '合同金额\n（万元）', name: 'contractAmountInTenThousands', width: 100 },
  { displayName: '是否联合体', name: 'isJointVenture', width: 100 },
  { displayName: '甲方联系人', name: 'partyAContactPerson', width: 100 },
  { displayName: '甲方电话', name: 'partyAPhone', width: 100 },
  { displayName: '甲方邮箱', name: 'partyAEmail', width: 100 },
  { displayName: '乙方项目经理', name: 'partyBProjectManager', width: 100 },
  { displayName: '服务类别', name: 'serviceCategory', width: 100 },
];
