export const defaultFormState = {
  name: '',
  department: '',
  manager: '',
  branch: '',
  delivery: false,
  businessType: '',
  resource: '',
  desc: '',
  anency: '',
  contractCode: '',
  contractName: '',
  invoiceFeeType: '',
  invoicePayType: '',
  paymentApplicationAttachments: [],
  invoiceSummaryAttachment: [],
  invoiceAcceptanceAttachment: [],
  invoiceOtherAttachment: [],
};
